"""description of changes

Revision ID: a3a1a668b61e
Revises: 43f5ce5951d0
Create Date: 2024-10-31 07:03:45.251776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from config.database import Base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3a1a668b61e'
down_revision: Union[str, None] = '43f5ce5951d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_info', sa.String(), nullable=False))
    op.add_column('task', sa.Column('datetime_to_do', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('task', 'updated_at')
    op.drop_column('task', 'created_at')
    op.drop_column('task', 'description')
    op.drop_column('todo_list', 'updated_at')
    op.drop_column('todo_list', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('todo_list', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('todo_list', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('task', 'datetime_to_do')
    op.drop_column('task', 'task_info')
    # ### end Alembic commands ###